package RedSocialTest.Enums;

public enum SocialResponseTypes {
    CREATED_POST,CONNECTION, FOLLOWER_MILE, ALREADY_FOLLOWING, ALREADY_LIKED, ALREADY_UNLIKED, UNACTIVE_ARTIST, GET_DOWN_SUCCSESSFULY, LIKES_MILE, SUCCESS_FOLLOWING,GET_ARTISTAS,GET_POSTS,GET_SEGUIDORES;
}
