package Enums;

public enum AuctionResponseType {
    SUBASTA_FINALIZADA,CONEXION_EXITOSA,GET_CLIENTS,SUBASTA_EXITOSA, BID_RESPONSE, APROBACION_OFERTA, AVISO_OFERTANTES, SUBASTA_CANCELADA, SEGUIR_SUBASTA_EXISTOSA;

}
